OPENNLP-1665 - Add PoC for OpenNLP gRPC Backend
apache/opennlp-sandbox pull request #197
Opened 2024-12-16 09:17 UTC by rzo1

Thank you for contributing to Apache OpenNLP.

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [x] Is there a JIRA ticket associated with this PR? Is it referenced 
     in the commit message?

- [x] Does your PR title start with OPENNLP-XXXX where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.

- [x] Has your PR been rebased against the latest commit within the target branch (typically main)?

- [x] Is your initial contribution a single, squashed commit?

### For code changes:
- [x] Have you ensured that the full suite of tests is executed via `mvn clean install` at the root opennlp-sandbox folder?
- [x] Have you written or updated unit tests to verify your changes?
- [x] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](https://www.apache.org/legal/resolved.html#category-a)? 
- [ ] If applicable, have you updated the LICENSE file, including the main LICENSE file in opennlp-sandbox folder?
- [ ] If applicable, have you updated the NOTICE file, including the main NOTICE file found in opennlp-sandbox folder?

### For documentation related changes:
- [x] Have you ensured that format looks appropriate for the output in which it is rendered?

### Note:
Please ensure that once the PR is submitted, you check GitHub Actions for build issues and submit an update to your PR as soon as possible.

2024-12-16 11:04 UTC, kinow approved these changes

2024-12-16 13:27 UTC, atarora commented on opennlp-grpc/README.md
> +This project demonstrates a proof of concept for creating a backend powered by Apache OpenNLP using gRPC. It comprises
```suggestion
This project demonstrates a proof of concept for creating a backend powered by Apache OpenNLP using gRPC. It comprises
```
```suggestion
This project demonstrates a proof of concept for creating a backend powered by Apache OpenNLP using gRPC. It comprises of three main modules : 
```

2024-12-16 13:27 UTC, atarora commented on opennlp-grpc/README.md
> +three main modules:
```suggestion

```

2024-12-16 13:29 UTC, atarora commented on opennlp-grpc/README.md
> +    - Provides a README with instructions on generating code stubs for various languages and auto-generated
```suggestion
    - Provides a README with instructions on generating code stubs for various languages and auto-generated documentation.
```

2024-12-16 13:29 UTC, atarora commented on opennlp-grpc/README.md
> +      documentation.
```suggestion
 
```

2024-12-16 13:32 UTC, atarora commented on opennlp-grpc/opennlp-grpc-api/README.md
> +The Java code can be (re)generated as follows; [docker-protoc](https://github.com/namely/docker-protoc) is used to
```suggestion
The Java code can be (re)generated as follows; [docker-protoc](https://github.com/namely/docker-protoc) is used to generate the code for Java : 
```

2024-12-16 13:32 UTC, atarora commented on opennlp-grpc/opennlp-grpc-api/README.md
> +generate the code for Java:
```suggestion

```

2024-12-16 13:32 UTC, atarora commented on opennlp-grpc/opennlp-grpc-api/README.md
> +Since the Java code is provided here and the corresponding JARs will be available from Maven, regenerating from the
```suggestion
Since the Java code is provided here and the corresponding JARs will be available from Maven, regenerating from the schema is not necessary.
```

2024-12-16 13:32 UTC, atarora commented on opennlp-grpc/opennlp-grpc-api/README.md
> +schema is not necessary.
```suggestion

```

2024-12-16 13:36 UTC, atarora approved these changes
Awesome work , Thanks @rzo1 !

2024-12-16 16:42 UTC, mawiesne requested changes
Thx @rzo1 - it's really a major contribution. I've left several comments giving opportunities to make it even stronger, more precise, and more lightweight.

2024-12-16 16:42 UTC, mawiesne commented on opennlp-grpc/examples/python-client/main.py
> +            model_hash='cb219de4e5fc8c3c6d61531ac2dff0b186f6c3f457207359ec28e9336311ef8e'  # Model name
"# Model name"  should read "# Model hash" ?

2024-12-16 16:42 UTC, mawiesne commented on opennlp-grpc/opennlp-grpc-api/README.md
> +It does not support every feature of Apache OpenNLP at the moment, but is open for enhancement or further improvement.
plural for "improvement"_s, as we want many of those :)

2024-12-16 16:42 UTC, mawiesne commented on opennlp-grpc/opennlp-grpc-api/README.md
> +	<dependencies>
No need to use `<dependencies>` and `</dependencies>` for this snippet. It's kind of bloatish.

2024-12-16 16:42 UTC, mawiesne commented on opennlp-grpc/opennlp-grpc-api/README.md
> +Since the Java code is provided here and the corresponding JARs will be available from Maven, regenerating from the
..."will be available from Maven" -> "will be available via Maven", use via here.

2024-12-16 16:42 UTC, mawiesne commented on opennlp-grpc/opennlp-grpc-api/opennlp.md
> +| PENN    | 1      |             |
The PENN row could have a description / note to indicate that this is a deprecated format and "back translation" from UD -> PENN isn't a loss-free operation.

2024-12-16 16:42 UTC, mawiesne commented on opennlp-grpc/opennlp-grpc-api/opennlp.proto
> +  // Assigns the sentence of tokens pos tags.
"pos" should be capitalized here: "POS" tags, as written below (in another comment)

2024-12-16 16:42 UTC, mawiesne commented on opennlp-grpc/opennlp-grpc-api/opennlp.proto
> +  // Assigns the sentence of tokens pos tags with additional (string-based) context.
See previous comment.

2024-12-16 16:42 UTC, mawiesne commented on opennlp-grpc/opennlp-grpc-service/pom.xml
> +            <version>4.2.2</version>
Externalize this version number towards a property?

2024-12-16 16:42 UTC, mawiesne commented on opennlp-grpc/opennlp-grpc-service/src/main/java/opennlp/OpenNLPServer.java
> + * It loads configuration settings from a file and uses them to initialize various components such as
"from a file" -> Indicate which one it is, aka what the name is?

2024-12-16 16:42 UTC, mawiesne commented on opennlp-grpc/opennlp-grpc-service/src/main/java/opennlp/OpenNLPServer.java
> + *   <li>{@code -h, --hostname}: Specifies the hostname to report (default is "localhost").</li>
"to report" -> see (earlier) comment above?

2024-12-16 16:42 UTC, mawiesne commented on opennlp-grpc/opennlp-grpc-service/src/main/java/opennlp/service/PosTaggerService.java
> +  public PosTaggerService(Map<String, String> conf) {
Please leave minimal JavaDoc for the constructor to explain how `conf` map is structured or should at least contain to be valid.

2024-12-16 16:42 UTC, mawiesne commented on opennlp-grpc/opennlp-grpc-service/src/main/java/opennlp/service/PosTaggerService.java
> +  public static void clearCaches() {
Pls, leave a short JavaDoc notice, in which situation caches should be evicted and/or what the (assumed) state is after the method has been invoked.

2024-12-16 16:42 UTC, mawiesne commented on opennlp-grpc/opennlp-grpc-service/src/main/java/opennlp/service/PosTaggerService.java
> +      final String[] tags = tagger.tag(request.getSentenceList().toArray(new String[0]), request.getAdditionalContextList().toArray(new String[0]));
Line is too long, pls reformat to increase readability.

2024-12-16 16:42 UTC, mawiesne commented on opennlp-grpc/opennlp-grpc-service/src/main/java/opennlp/service/PosTaggerService.java
> +        return new ThreadSafePOSTaggerME(new POSModel(new ByteArrayInputStream(model.model())), format);
Should additionally be wrapped in a `BufferedInputStream` to speed up reading of larger models.

2024-12-16 16:42 UTC, mawiesne commented on opennlp-grpc/opennlp-grpc-service/src/main/java/opennlp/service/classpath/DirectoryModelFinder.java
> +public class DirectoryModelFinder extends AbstractClassPathModelFinder implements ClassPathModelFinder {
Is this a candidate for inclusion in: `opennlp-tools-models` component? Open a Jira to transfer / include it there?

2024-12-16 16:42 UTC, mawiesne commented on opennlp-grpc/opennlp-grpc-service/src/main/java/opennlp/service/classpath/DirectoryModelFinder.java
> +   * @param directory      the root directory to search for model files; must not be {@code null}.
"search" -> "scan"

2024-12-16 16:42 UTC, mawiesne commented on opennlp-grpc/opennlp-grpc-service/src/main/java/opennlp/service/classpath/DirectoryModelFinder.java
> +    final Pattern jarPattern = Pattern.compile(asRegex("*" + getJarModelPrefix()));
Make `jarPattern` a constant?

2024-12-16 16:42 UTC, mawiesne commented on opennlp-grpc/opennlp-grpc-service/src/main/java/opennlp/service/classpath/DirectoryModelFinder.java
> +    final Pattern filePattern = Pattern.compile(asRegex("*" + wildcardPattern));
Make `filePattern` a constant?

2024-12-16 16:42 UTC, mawiesne commented on opennlp-grpc/opennlp-grpc-service/src/test/java/opennlp/service/PosTaggerServiceTest.java
> +    return Paths.get(
lines 40 to 44 look a bit weirdly in terms of formatting, might be improved towards better readability.

2024-12-16 16:42 UTC, mawiesne commented on opennlp-grpc/opennlp-grpc-service/src/test/java/opennlp/service/PosTaggerServiceTest.java
> +    final String[] sentence = {"The", "driver", "got", "badly", "injured", "by", "the", "accident", "."};
The reference sentence and POS tags array can be externalized to a constant to avoid duplication.

2024-12-16 16:42 UTC, mawiesne commented on opennlp-grpc/opennlp-grpc-service/src/test/java/opennlp/service/PosTaggerServiceTest.java
> +    PosTaggerService.clearCaches();
This line / call should be externalized in form of an `@AfterEach` annotated cleanup method in that test. 

See below for other, multiple occurrences.

2024-12-16 16:42 UTC, mawiesne commented on opennlp-grpc/opennlp-grpc-service/src/test/resources/models/opennlp-models-pos-en-1.2.0.jar
Can we avoid adding (larger) binary model resources to the /src/test/resources/models folder? This is a liability for the future and means extra cost in transfer (scm checkouts) and disk space requirements.

2024-12-16 16:42 UTC, mawiesne commented on opennlp-grpc/pom.xml
> +        <opennlp.version>2.5.1</opennlp.version>
That property should be defined already via the parent sandbox pom.xml file? same with junit and slf4j, log4j2. Why don't we re-use this, when this pom.xml file points to a parent that has it already defined?

2024-12-16 16:42 UTC, mawiesne commented on pom.xml
> +        <module>opennlp-grpc</module>
When adding this here, the upper READM.md file in the root of the sandbox needs an addition for that set of components, as everything should be basically introduced there, at least the name and a short description.

2024-12-16 17:06 UTC, rzo1 commented on opennlp-grpc/opennlp-grpc-api/opennlp.proto
> +  // Assigns the sentence of tokens pos tags.
Capital Letters violate gRPC naming convention. Leaving as is.

2024-12-16 17:10 UTC, mawiesne commented on opennlp-grpc/opennlp-grpc-api/opennlp.proto
> +  // Assigns the sentence of tokens pos tags.
Cave: I meant the comment not the name of the service

2024-12-16 17:10 UTC, mawiesne commented on opennlp-grpc/opennlp-grpc-api/opennlp.proto
> +  // Assigns the sentence of tokens pos tags with additional (string-based) context.
Cave: I meant the comment not the name of the service

2024-12-16 19:10 UTC, rzo1 commented on opennlp-grpc/README.md
> +-h or --hostname: Hostname to report (default: localhost).
Actually, this isn't used (and is a leftover). Will drop.

2024-12-16 19:30 UTC, rzo1 commented on opennlp-grpc/opennlp-grpc-service/src/main/java/opennlp/service/classpath/DirectoryModelFinder.java
> +    final Pattern jarPattern = Pattern.compile(asRegex("*" + getJarModelPrefix()));
Cannot be a constant here but we can avoid creating it on each method call.

2024-12-16 19:30 UTC, rzo1 commented on opennlp-grpc/opennlp-grpc-service/src/main/java/opennlp/service/classpath/DirectoryModelFinder.java
> +    final Pattern filePattern = Pattern.compile(asRegex("*" + wildcardPattern));
Cannot be a constant here but we can avoid creating it on each method call.

2024-12-16 19:33 UTC, rzo1 commented on opennlp-grpc/opennlp-grpc-service/src/test/resources/models/opennlp-models-pos-en-1.2.0.jar
the jar is now copied via Maven from the local repository (or remote) via mvn dependency plugin.

2024-12-16 19:34 UTC, rzo1 commented on opennlp-grpc/opennlp-grpc-service/src/main/java/opennlp/service/PosTaggerService.java
> +  public static void clearCaches() {
added docs

2024-12-16 19:34 UTC, rzo1 commented on opennlp-grpc/opennlp-grpc-service/src/main/java/opennlp/service/PosTaggerService.java
> +  public PosTaggerService(Map<String, String> conf) {
added docs

2024-12-16 19:35 UTC, rzo1 commented on opennlp-grpc/opennlp-grpc-service/src/main/java/opennlp/service/classpath/DirectoryModelFinder.java
> +public class DirectoryModelFinder extends AbstractClassPathModelFinder implements ClassPathModelFinder {
Can be moved after sandbox phase.

2024-12-16 19:40 UTC, rzo1 commented
Thanks for the reviews. Added the related changes.

2024-12-17 05:43 UTC, mawiesne approved these changes
Thx @rzo1 for this major contribution!

2024-12-17 09:47 UTC, merged